name: Continous deployment of firebase functions to Firebase project

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: Install npm packages
        working-directory: functions
        run: npm install

      - name: Add sokxay.json file
        working-directory: functions
        run: echo -e ${{ secrets.SOKXAY }} >> sokxay.json

      - name: Deploy function to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
