name: Continous deployment of firebase functions to Firebase project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: Install npm packages
        working-directory: functions
        run: npm install

      - name: Deploy function to Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
